# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins: [jekyll-paginate]

# Setup
title:            Quinson
tagline:          'Hon Kwan Shun Quinson's Profile'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://hksquinson.github.io/portfolio/
baseurl:          /

author:
  name:           'Hon Kwan Shun Quinson'
  url:            https://hksquinson.github.io/portfolio/

paginate:         5

# Custom vars
version:          b0.0.1

github:
  repo:           https://hksquinson.github.io/portfolio/
