# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins: [jekyll-paginate]

# Setup
title:            "Quinson's Profile"
tagline:          "Hon Kwan Shun Quinson's Profile"
description:      'A Final-year artificial intelligence undergraduate in CUHK'
url:              https://hksquinson.github.io/
baseurl:          '/'

author:
  name:           'Hon Kwan Shun Quinson'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/poole/hyde
