# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins: 
  - jekyll-paginate

# Setup
title:            "Quinson's Profile"
tagline:          "Hon Kwan Shun Quinson's Profile"
description:      'A Final-year artificial intelligence undergraduate in CUHK'
url:              https://hksquinson.github.io/profile/
baseurl:          '/'

author:
  name:           'Hon Kwan Shun Quinson'
  url:            https://twitter.com/mdo

paginate:         5 # default for all below; will be overridden by `per_page` value
pagination: 
  - paginate:
      path:       /page:num/
      per_page:   5

collections:
  experiences:
    output: true
    permalink: /experiences/:path/

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/poole/hyde


