# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

plugins: 
  - jekyll-paginate

# Setup
title:            "Quinson's Profile"
tagline:          "Hon Kwan Shun Quinson's Profile"
description:      'Final-year undergraduate student at the Chinese University of Hong Kong'
url:              https://hksquinson.github.io/profile/
baseurl:          '/'

author:
  name:           'Hon Kwan Shun Quinson'
  url:            https://hksquinson.github.io/profile/

paginate:         5 # default for all below; will be overridden by `per_page` value
pagination: 
  - paginate:
      path:       /page:num/
      per_page:   5

collections:
  experiences:
    output: true
    permalink: /experiences/:path/
  news:
    output: true
    permalink: /news/:path/

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/hksquinson/profile


